//! Byte-level ground-truth alignment with upstream pi's mid-conversation
//! system messages (#9548). The fixture was generated by running UPSTREAM
//! TypeScript sources (`packages/ai/src/utils/transcript.ts` + `text.ts`,
//! plus `withToolChanges` from `agent-loop.ts`) through esbuild+node — not
//! by re-deriving expected values by hand.
//!
//! Comparisons are SEMANTIC JSON equality (serde_json::Value), i.e.
//! byte-level modulo object key order. Byte-identical key order is
//! impossible to define: upstream itself serializes these objects with
//! DIFFERENT key orders depending on the construction path —
//! `createInitialSystemMessage` and `getCurrentSystemMessage` emit
//! `{role, content, toolsAdded?, timestamp}` (timestamp last), while
//! `withToolChanges` (the agent-loop declare path) emits `{role, content,
//! sections?, timestamp, toolsAdded?, toolsRemoved?}` (timestamp before
//! the tool fields). tack serializes uniformly in interface declaration
//! order (`role, content, sections?, toolsAdded?, toolsRemoved?,
//! timestamp`), which matches the first two paths byte-for-byte.

#![allow(clippy::unwrap_used)]

use serde_json::Value;
use tack_ai::transcript::{
    self, ToolStateChanges, collapse_system_messages, create_initial_system_message,
    get_current_system_message, get_current_system_prompt, get_current_tools,
    get_tool_state_changes, with_tool_changes,
};
use tack_ai::{Message, SystemMessage, ToolDefinition, ToolReference, UserContent};

fn ground_truth() -> Value {
    serde_json::from_str(include_str!("fixtures/transcript_ground_truth.json")).unwrap()
}

/// tool(name, desc) exactly as the generator defined it.
fn tool(name: &str, desc: Option<&str>) -> ToolDefinition {
    ToolDefinition {
        name: name.to_string(),
        description: desc
            .map(str::to_string)
            .unwrap_or_else(|| format!("{name} tool")),
        parameters: serde_json::json!({
            "type": "object",
            "properties": { "q": { "type": "string" } }
        }),
        defer_loading: false,
        constrained_sampling: None,
    }
}

fn system(
    content: &str,
    sections: Option<&[(&str, Option<&str>)]>,
    tools_added: Option<Vec<ToolDefinition>>,
    tools_removed: Option<Vec<ToolReference>>,
    timestamp: u64,
) -> SystemMessage {
    SystemMessage {
        content: UserContent::Text(content.to_string()),
        sections: sections.map(|pairs| {
            pairs
                .iter()
                .map(|(k, v)| (k.to_string(), v.map(str::to_string)))
                .collect()
        }),
        tools_added,
        tools_removed,
        timestamp,
    }
}

fn reference(name: &str) -> ToolReference {
    ToolReference {
        name: name.to_string(),
    }
}

/// The generator's `transcript` (m1..m4), verbatim.
fn scenario_transcript() -> Vec<Message> {
    vec![
        Message::System(system(
            "base prompt",
            Some(&[("preamble", Some("P")), ("cwd", Some("/work"))]),
            Some(vec![tool("read", None), tool("bash", None)]),
            None,
            1000,
        )),
        Message::User(tack_ai::UserMessage {
            content: UserContent::Text("hi".to_string()),
            timestamp: 2000,
        }),
        Message::System(system(
            "",
            Some(&[("cwd", Some("/repo")), ("docs", None)]),
            None,
            Some(vec![reference("bash")]),
            3000,
        )),
        Message::System(system("extra instructions", None, None, None, 4000)),
    ]
}

#[test]
fn initial_system_message_matches_upstream() {
    let gt = ground_truth();
    let initial =
        create_initial_system_message(Some("You are helpful."), Some(&[tool("read", None)]))
            .expect("non-empty");
    assert_eq!(
        serde_json::to_value(Message::System(initial)).unwrap(),
        gt["initial"]
    );

    // Empty prompt AND empty tools -> undefined (null in the fixture).
    assert!(create_initial_system_message(Some(""), Some(&[])).is_none());
    assert!(create_initial_system_message(None, None).is_none());
}

#[test]
fn replay_matches_upstream() {
    let gt = ground_truth();
    let transcript = scenario_transcript();

    let current = get_current_system_message(&transcript).expect("has system state");
    assert_eq!(
        serde_json::to_value(Message::System(current)).unwrap(),
        gt["currentSystem"]
    );

    let tools = get_current_tools(&transcript);
    assert_eq!(serde_json::to_value(&tools).unwrap(), gt["currentTools"]);

    let prompt = get_current_system_prompt(&transcript);
    assert_eq!(serde_json::to_value(&prompt).unwrap(), gt["currentPrompt"]);

    let collapsed = collapse_system_messages(&transcript);
    assert_eq!(
        serde_json::to_value(&collapsed).unwrap(),
        gt["collapsed"]["messages"]
    );
}

#[test]
fn tool_state_changes_match_upstream() {
    let gt = ground_truth();

    let changes = get_tool_state_changes(
        &[tool("read", None), tool("bash", None)],
        &[tool("read", Some("read v2")), tool("edit", None)],
    );
    assert_eq!(
        serde_json::json!({
            "toolsAdded": changes.tools_added,
            "toolsRemoved": changes.tools_removed,
        }),
        gt["changes"]
    );

    let updated = with_tool_changes(
        &system("", None, None, None, 5000),
        &ToolStateChanges {
            tools_added: changes.tools_added.clone(),
            tools_removed: changes.tools_removed.clone(),
        },
    );
    assert_eq!(
        serde_json::to_value(Message::System(updated)).unwrap(),
        gt["withChanges"]
    );

    // Empty changes clear previously declared tool fields entirely.
    let cleared = with_tool_changes(
        &system(
            "x",
            Some(&[("a", Some("1"))]),
            Some(vec![tool("z", None)]),
            None,
            6000,
        ),
        &ToolStateChanges::default(),
    );
    assert_eq!(
        serde_json::to_value(Message::System(cleared)).unwrap(),
        gt["withChangesEmpty"]
    );
}

/// Upstream-shaped system messages parse losslessly (any key order, all
/// optional fields present or absent) and re-serialize to the same value.
#[test]
fn upstream_system_message_json_round_trips() {
    let raw = serde_json::json!({
        "role": "system",
        "content": "base prompt",
        "sections": { "preamble": "P", "docs": null },
        "toolsAdded": [{
            "name": "read",
            "description": "read tool",
            "parameters": { "type": "object" }
        }],
        "toolsRemoved": [{ "name": "bash" }],
        "timestamp": 1735689600000u64
    });
    let message: Message = serde_json::from_value(raw.clone()).unwrap();
    let Message::System(system) = &message else {
        panic!("expected system message, got {message:?}");
    };
    assert_eq!(system.timestamp, 1735689600000u64);
    assert_eq!(
        system.sections.as_ref().unwrap().get("docs"),
        Some(&None),
        "null section values survive (section removal)"
    );
    assert_eq!(serde_json::to_value(&message).unwrap(), raw);

    // Block content form: string | TextContent[].
    let raw = serde_json::json!({
        "role": "system",
        "content": [{ "type": "text", "text": "hello" }],
        "timestamp": 1
    });
    let message: Message = serde_json::from_value(raw.clone()).unwrap();
    assert_eq!(serde_json::to_value(&message).unwrap(), raw);
    let Message::System(system) = message else {
        panic!()
    };
    assert_eq!(transcript::content_text(&system.content), "hello");
}

/// Byte-level identity (key order included) for the compaction
/// `systemMessage` path: upstream's `appendCompaction` writes
/// `{ ...getCurrentSystemMessage(...), timestamp }` — role, content,
/// sections?, toolsAdded?, timestamp — exactly tack's struct order.
#[test]
fn compaction_system_message_is_byte_identical_to_upstream() {
    let system = SystemMessage {
        content: UserContent::Text(String::new()),
        sections: Some(
            [(
                "system-prompt".to_string(),
                Some("You are Tack.".to_string()),
            )]
            .into_iter()
            .collect(),
        ),
        tools_added: Some(vec![ToolDefinition {
            name: "read".to_string(),
            description: "read tool".to_string(),
            parameters: serde_json::json!({"type": "object"}),
            defer_loading: false,
            constrained_sampling: None,
        }]),
        tools_removed: None,
        timestamp: 1767225602000,
    };
    let mut buf: Vec<u8> = Vec::new();
    {
        let mut ser = serde_json::Serializer::new(&mut buf);
        tack_ai::serde_system_message::serialize(&Some(system), &mut ser).unwrap();
    }
    // Generated from upstream sources (getCurrentSystemMessage + the
    // appendCompaction spread, run through node).
    let upstream = r#"{"role":"system","content":"","sections":{"system-prompt":"You are Tack."},"toolsAdded":[{"name":"read","description":"read tool","parameters":{"type":"object"}}],"timestamp":1767225602000}"#;
    assert_eq!(String::from_utf8(buf).unwrap(), upstream);
}
